<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-09-20 14:10
=======
# Generated by Django 2.2.4 on 2019-09-23 18:58
>>>>>>> 0533f8d1619755e730830e7626d67534ca7be334

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('follower_id', models.CharField(max_length=100)),
=======
                ('follow_id', models.CharField(max_length=100)),
>>>>>>> 0533f8d1619755e730830e7626d67534ca7be334
                ('following_id', models.CharField(max_length=100)),
            ],
        ),
    ]
