# Generated by Django 2.2.5 on 2019-09-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_id',
            new_name='follower_id',
        ),
    ]
