# Generated by Django 2.2.5 on 2019-10-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
