# Generated by Django 2.2.4 on 2019-08-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, default="your name's", max_length=30, null=True)),
            ],
        ),
    ]
