# Generated by Django 2.2.4 on 2019-09-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
