# Generated by Django 2.2.4 on 2019-09-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20190901_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todouser', models.CharField(max_length=30)),
                ('todotask', models.TextField(blank=True, default='Task to do', max_length=30, null=True)),
            ],
        ),
    ]
