# Generated by Django 2.2.4 on 2019-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_id', models.CharField(max_length=100)),
                ('following_id', models.CharField(max_length=100)),
            ],
        ),
    ]
